### ISSUE TITLE
python config for example chains

### ISSUE THREAD

**Issue by timadye** [acts-project/acts#1098]
Discuss the best way to organise the Python in `Examples/Scripts/Python` to allow configuration of various full-chain examples.

Some ideas already in #1093 and #1096. @asalzburger suggested he and I post further ideas as comments, and we can discuss at the dev meeting.

CC @paulgessinger

**Comment by timadye** [comment]
Here are some of my thoughts...

Most of the current examples in `Examples/Scripts/Python` seem to be complete examples that run

1. evgen
2. geometry
3. fatras
4. digitization
5. seeding
6. track finding

at least up to the step being tested. I think it would be easier and clearer to have each step defined in a stand-alone routine (in its own `import`) and have the current `runParticleGun`, `runFatras` functions call them. Some of those might want different settings for the preceding steps (eg. different number of particles for evgen), so the `run*` routines may have to change some defaults.

Orthogonal to this, it would also be useful to have one or more full-chain tests, where the different options can be specified with command-line options. Probably it is simpler to have separate Python main commands for Generic, ODD (or all DD4hep?) , and ATLAS (or all TGeo?) detectors. It would be good if these could be small scripts that set the appropriate defaults and call the other modules. It would also be clearer if the `argparse` option setup and overall defaults were defined in the appropriate modules.

Eg. `fatras.py` could contain the following:

* `addFatras(s,**opts)`: configure `ParticleSelector` and `FatrasSimulation`, and add them to the sequence, `s`. Or should it return the algorithms and let the user add them? Perhaps complicated for the user if there are optional additional algorithms, like printing or dumping the output.
* `optFatras(p)`: contains several `p.add_argument()`s to define all the Fatras options.
* `runFatras()`: same as current definition, but uses `addParticleGun()` and `addFatras()`
* main: same as current definition

One problem with this is that `addFatras()` can be passed Python function arguments or the result of `p.parse_args()` (a simple `argparse.Namespace` object, convertible to a `dict` with `vars()`). Do we want `addFatras()` to merge common options, or require the user to convert to one or the other? I don't know if it is too complicated, but there is some advantage to making all options be specified with `argparse`. That gives automatic documentation and greatest flexibility, but probably makes the Python more complicated than it need be.

Here is an example of how `runFatras` would work if we made all options potential command-line options:
```
def runFatras(outputDir):
  import particle_gun, generic_detector

  p = argparse.ArgumentParser()   # or have something in common.py to add common options like --loglevel
  optParticleGun(p)
  optGenericDetector(p)
  optFatras(p)
  p.set_defaults(opt.output_dir = outputDir)   # if we still want the caller to be able to set this
  opt = p.parse_args()

  s = Sequencer(events=events, numThreads=-1, outputDir=opt.output_dir,
                logLevel=opt.loglevel)  # or something in common.py
  addParticleGun(s, opt)
  addGenericDetector(s, opt)
  addFatras(s, opt)

  s.run()
```
In this case, we are only using `argparse` to set the defaults. The user doesn't have to set any options.

Here are some ideas for what we might define:

1. `addParticleGun`
2. `addPythia8`
3. `addEventGenerator`: common interface for `runParticleGun` or `runPythia8`, depending on options
4. `addFatras`: `ParticleSelector` + `FatrasSimulation`
5. `addDigitization`: `DigitizationAlgorithm`
6. `addSeeding`: `TruthSeedSelector` + (`ParticleSmearing`[truthSmearedSeeded] OR `SpacePointMaker`+`SeedingAlgorithm`) + performance plots
7. `addCKFTracks`: `TrackFindingAlgorithm` + `CKFPerformanceWriter`?

and similar `run*` and `opt*` routines. Most steps should be able to read from a previous step (with a fixed name?) or from a file. Most should also be able to write to a file.

**Comment by paulgessinger** [comment]
Hey @timadye, thanks for the elaborate proposal.

My worry with liberally using `argparse` is that it kind of brings us all the way back around to what we had (have) with `boost::program_options`, with the same drawbacks (having to put everything into options to be usable, having a bunch of different executables) but in python instead of C++.

I guess my original idea was to have these python scripts deliberately have overlaps and hard-coded settings, with the intention of them being actual examples. You open the e.g. `seeding.py` and you can read off all the different steps that we do to run the seeding. Now if you want to use a different input, you can change `seeding.py` in-place to make the changes you want (different detector, different B-field, etc), or you copy (part of) `seeding.py` and customize it further. This comes at the cost of code-duplication.

In a number of interactions I had with various people, it seemed to me like our current *examples* (the C++ ones), didn't really serve as examples at all: people searched for the executable that did more-or-less what they were looking to do, and ran that with various degrees of complex program options. I think we should try to move away from this, and encourage people more to assemble their exact sequence by reading the python example scripts.

The primary reason I added the `runX` functions to begin with was to be able to run them from the `pytest` tests.

In my opinion, we should only add `argparse` if there's a limited subset of options/arguments that we actually want to be changeable from the command line, say different input files, or the exact range of a particle gun, or so.

In addition, I think it's fine to have helper functions for certain things where we have a *recommended* way of doing something, or were something is only done in a certain way, but requires multiple components. An example of this would be `getOpenDataDetector`, or maybe something like "read particles from this file into this collection" or "select particles with some pt threshold".

**Comment by asalzburger** [comment]
Hi @paulgessinger @timadye - this is what I wanted to spark here by asking @timadye to open this issue. I think we should decouple the discussion into two blocks:

1.  The functions that build a job:

Here, I would strongly recommend the possibility of chaining functions together, e .g.

```python
def runParticleGeneration(s, ...) 
```

and successively, digitization and Fatras:

```python
def runDigitization(s, ...)
```

and 
```python
def runFatras(s, ...)
```

When these could run in parallel or, as a chained example:

```python 
# Create a sequencer
s = acts.Examples.Sequencer(threads=-1, events=100)
# Now chain
s = runParticleGeneration(s, ...)
s = runDigitization(s, ...)
s = runFatras(s, ...)
```

The functions should be configurable, and be able to add their appropriate output (in #1093 I steer the output by existence of an `outputDirCsv` or `outputDirRoor` string), we can either make the container types fixed , or make a simple dictionary that is handed over.

2. The full chain examples

This is what I understand @timadye is relating here, and there we should discuss how to provide them (and how much we actually have to provide them if the first point is transparently done).

**Comment by asalzburger** [comment]
Suggestion by @paulgessinger 

Split into `addParticleGeneration(...)` and a `runParticleGeneration(...)` with the latter to be run in the pytests.

**Comment by asalzburger** [comment]
Action items:
 * make a template with `particle_gun` and `digitization`, `fatras`

**Comment by timadye** [comment]
I've been implementing this for `particle_gun` and `fatras` ([branch](https://github.com/timadye/acts/tree/pybind4) still under development).

A couple of questions:
1. Should we use `pathlib.Path` to pass `outputDirCsv` and `outputDirRoot`? Currently they are just `str`.
2. Do we need to worry about `RandomNumbers`? If we keep the same structure, `addParticleGun` and `addFatras` each has their own sequence (and seed), while the old all-in-one `runFatras` uses a single sequence.

@asalzburger, I notice that your proposal above you have
```

**Comment by paulgessinger** [comment]
My 2 cents:

1. I like `pathlib.Path`, so I'd be in favor of using that. Ultimately up to you though.
2. I think the `RandomNumbers` instance should be an argument to the `addXYZ` functions, and you pass it in from the outer script? Or am I missing the point.

**Comment by timadye** [comment]
> 1. I like `pathlib.Path`, so I'd be in favor of using that. Ultimately up to you though.

I went with `pathlib.Path`, but put in a conversion for compatibility in case it is passed a `str`.

> 2. I think the `RandomNumbers` instance should be an argument to the `addXYZ` functions, and you pass it in from the outer script? Or am I missing the point?

That's what I did. If you don't pass it in, it makes a new one.

**Comment by timadye** [comment]
Sorry, this is still being worked on in #1128.

**Comment by timadye** [comment]
I have opened #1174 to follow the continuing work on this feature.

**Comment by timadye** [comment]
#1174 has been merged, completing this work
