### ISSUE TITLE
Bug: nullptr segv in Navigator::reset

### ISSUE THREAD

**Issue by wdconinc** [acts-project/acts#1106]
I am encountering a segfault in Navigator::reset when startLayer is nullptr. It is very likely a symptom of another as-yet-unidentified issue on our side, but nevertheless it may make sense to consider whether this is intended behavior.

Here is the relevant bit in `Navigator::reset`:
```
      // Reset everything first
      *this = State();

      // Set the start, current and target objects
      startSurface = ssurface;
      if (ssurface->associatedLayer() != nullptr) {
        startLayer = ssurface->associatedLayer();
      }
      if (startLayer->trackingVolume() != nullptr) {
        startVolume = startLayer->trackingVolume();
      }
      currentSurface = startSurface;
      currentVolume = startVolume;
      targetSurface = tsurface;
```
In our case this seems to lead to the following sequence:
1. set all relevant variables to nullptr,
2. `ssurface->associatedLayer()` is nullptr, so `startLayer` is not set (and remains nullptr),
3. `startLayer->trackingVolume()` segfaults because `startLayer` is still nullptr.

Reproducability... I don't have a minimal working example... We encounter this issue in our EIC ATHENA track reconstruction code when upgrading from working 14.1.0 to 15.0.0 with this issue, i.e. https://eicweb.phy.anl.gov/EIC/juggler/-/merge_requests/362 (stracktrace there). I'm likely still missing something in the upgrade that causes this regression, but nevertheless it seems that there is a possibility for segfaults based on the code alone.

Relevant frames in stacktrace:
```
#6  <signal handler called>
#7  Acts::Layer::trackingVolume (this=0x0) at /opt/software/linux-ubuntu21.10-skylake/gcc-11.2.0/acts-15.0.0-npmpkqnurev5jrzo3fjgqlgeczuf6elo/include/Acts/Geometry/detail/Layer.ipp:31
#8  Acts::Navigator::State::reset (this=this
entry=0x7ffd973e34a0, geoContext=..., pos=..., dir=..., navDir=Acts::forward, ssurface=0x55e4f4d84060, tsurface=0x0) at /opt/software/linux-ubuntu21.10-skylake/gcc-11.2.0/acts-15.0.0-npmpkqnurev5jrzo3fjgqlgeczuf6elo/include/Acts/Propagator/Navigator.hpp:235
```

**Comment by wdconinc** [comment]
OT: Bug report checklist asks to label issues, but regular users cannot assign labels. I'd have labeled 'Impact - Minor'.

**Comment by paulgessinger** [comment]
Hey @wdconinc, thanks for the bug report. I don't have any immediate ideas why this would occur, I don't think I've ever seen this happen in any other context. Most likely we never run into a case where `reset` is called with an `ssurface` that doesn't have a layer. This is weird though because it seems this simply happens in the CKF when it switches context. I did some changes in the CKF for `v15.0.0`, but I never observed any failures like this.

I agree the logic itself doesn't cover this case at all, the second if should be protected in case there is no `startLayer`.
I suppose the least that can be done is add an extra `if` to catch this case.

One thing I noticed when looking at the MR over on your Gitlab is that you copied the pattern from our fitting algorithm, where I introduced an `std::list` to have stable pointers for the source links I create. This is not necessarily a good idea for a setup meant for any kind of production: `std::list` is relatively slow. I didn't add anything more clever to that algorithm there because it wasn't needed, but I would suggest you try to work around using this pattern, for example by creating the source links in one pass and only afterwards creating the measurements (when source link pointers are stable)

**Comment by asalzburger** [comment]
Hi,

this looks like a logic bug, there's no guarantee that the startSurface has a layer associated, so it potentially can be unset.
In case of an unset startLayer a global search should termite it, i.e. you search the volume associated to the global position and then the layer according to the position.

**Comment by asalzburger** [comment]
Discussing with @paulgessinger - this is in the CKF, so the `ssurface` should indeed have an `associateLayer`, unless it is hidden somewhere, i.e. when the layer is built, is does not appear in the `surfaceArray()` list of surface, which are eventually associated with the layer.

One quick check, can you please dump the `GeometryId` of the start surface?

**Comment by wdconinc** [comment]
After further investigation (and a holiday break in the middle) and as you already hinted at, this turned out to be due to a remaining `m_geometryId` that was left over in our IndexSourceLink class from before IndexSourceLink was a class in Core. That value of `m_geometryId` was never initialized and therefore led to undefined measurement surfaces.

I appreciate the comments on the performance of using `std::list` and we will address those in our code.

I'm going to be closing this issue since it has been resolved.
