### ISSUE TITLE
Overlapping volumes exception for ITk geometry

### ISSUE THREAD

**Issue by timadye** [acts-project/acts#1144]
Since #1090, the current ITk TGeo geometry throws an `invalid_argument` exception:
```
Volumes are overlapping, this shouldn't be happening. Please check your geometry building.
```

This seems to be due to an overlap between volumes at
 * R =  0.0        –   30.4     mm (BeamPipe); and
 * R = 29.8228 – 128.027 mm (barrel InnerPixels)

`TGeoDetector` adds a 1mm envelope to both the beampipe and the pixel inner radius, which is included in the overlap check and the numbers above. Reducing this envelope prevents the crash.

One likely fix for this issue is to [`acts-detector-examples`](https://gitlab.cern.ch/acts/acts-detector-examples), but I post the issue here so it can be discussed more widely.

**Comment by noemina** [comment]
If I understand correctly, this issue is due to these lines where an envelope in R is configured for the beam-pipe and pixel volumes.

For the beampipe layer builder configuration we add +1 mm on the outer radius:
https://github.com/acts-project/acts/blob/853f9b70551667209ba6b56deaccf111d3fc33a4/Examples/Detectors/TGeoDetector/src/TGeoDetector.cpp#L203-L204

A few lines below this is also configured to happen for the pixel layer, where now add +1 mm on the inner radius (and +5 mm on the outer radius) :
https://github.com/acts-project/acts/blob/853f9b70551667209ba6b56deaccf111d3fc33a4/Examples/Detectors/TGeoDetector/src/TGeoDetector.cpp#L268-L269

As suggested by Tim, either we decide to reduce the envelopes (I have tested 0.5 prevents the crash), or we can add this additional configuration parameter for the `TGeoDetector` config.

**Comment by noemina** [comment]
Ah, comparing with the current implementation in athena, the beampipe radius is set to 23.934 mm, while in the json file we have  29.0 mm. I would suggest we can switch to this value in the json and maintain the generous envelopes then.

**Comment by noemina** [comment]
This is now fixed as the beampipe parameter has been updated in https://gitlab.cern.ch/acts/acts-detector-examples/-/merge_requests/12

**Comment by timadye** [comment]
Hi @noemina,
Thanks for tracking down the best fix!
Just for the record, we also need to fix [itk.py](https://github.com/acts-project/acts/blob/main/Examples/Scripts/Python/itk.py#L119). I tested the fix there too, but am looking at the same code for #1149 so if there's another fix we can do both together if you like.

**Comment by noemina** [comment]
Yes, I can help you with that!

**Comment by paulgessinger** [comment]
That'd be great @timadye.
