### ISSUE TITLE
Seeding grid phi binning has changed 

### ISSUE THREAD

**Issue by osbornjd** [acts-project/acts#1172]
The seeding algorithm has changed in a nontrivial way in regards to the way that the grid binning is determined. In previous versions, e.g. 1.1, the space point grid binning was determined by the maximum deflection angle as seen [here](https://github.com/acts-project/acts/blob/836fddd02c3eff33825833ff97d6abda5b5c20a0/Core/include/Acts/Seeding/SpacePointGrid.ipp#L37). In the latest version, there are additional components that lead to different phi binning for the same input configuration parameters due to the addition of `deltaAngleWithMaxD0` as well as the dividing by the number of phi neighbors as seen [here](https://github.com/acts-project/acts/blob/b8abfb54cbb6561337be82c6ad0dd1c12609f35b/Core/include/Acts/Seeding/SpacePointGrid.ipp#L58). Is the effect of this change completely understood? It changes the underlying binning of the grid, which may or may not impact physics and/or CPU timing performance (that is still to be determined for the case of sPHENIX, not sure if other experiments have seen changes).

**Comment by paulgessinger** [comment]
This was largely the work of @LuisFelipeCoelho towards making the ACTS seeding perform (or able to be configured to perform) identically to the ATLAS seeding for ITk. 

I believe the changes are in fact understood overall (I'll let @LuisFelipeCoelho and @noemina comment on this).

We unfortunately still don't have detailed distribution level physics performance monitoring, but we do have the ROOT hash monitoring, and changes to the output were investigated.

**Comment by robertlangenberg** [comment]
Joe had told me the parameter deltaAngleWithMaxD0 leads to MORE phi-bins, which would be counter-intuitive. it should be less than before. If numPhiNeighbors=1 there shouldn't be an increase in the number of phi-bins if i'm not mistaken

**Comment by noemina** [comment]
As you say, the parameter deltaAngleWithMaxD0 leads to a larger expected deflection in phi and should reduce the number of bins. I think is the change in the denominator that increases the number of bins (there was no denominator in the previous version of the code).

> If numPhiNeighbors=1 there shouldn't be an increase in the number of phi-bins if i'm not mistaken

In terms of number of bins, the previous value is obtainable if numPhiNeighbors=0, not 1. This has been indeed added to configure consistently the number of bins in the grid and the bin finder.

**Comment by robertlangenberg** [comment]
Hi @noemina sorry for having this discussion spread out, I'll try to recap what I said and your response on #1167. 
I said
> a single phi bin should cover the maximum deflection in phi such that looking at a single neighbor should be enough as long as numPhiNeighbors is 1

and your response was 
> That's exactly what it does. We didn't change the logic there.

On this ticket you say numPhiNeighbors should be 0 to match the previous behavior. If numPhiNeighbors=1 triples the number of phiBins, the phiBins won't cover the full deflection in phi (i.e. we'd have to look at least at 3 neighbors in each direction to find all seeds.

**Comment by noemina** [comment]
Hello, 
sorry for not being clear. I think we need to consider two things here: number of bins in phi in the grid and how many of those bins we use for the space point search to build seeds. Of course the two things are very much correlated.

If numPhiNeighbors=1, for a given phi bin for the central point, we consider 3 consecutive phi bins for top and bottom SP search (stealing this picture from one of Max's talk):
![image](https://user-images.githubusercontent.com/58694235/154940736-24b4df3c-77a4-48be-8871-8feec943c8d2.png)

In order to be efficient and suppress combinatorics, which means that the size of these regions should be sufficient to accommodate trajectory of low-pt tracks but not too wide, we have evaluated that each phi bin should be a third of the maximum expected azimuthal deflection, provided by the factor (2*N+1) in the denominator.

If I am not mistaken, the previous implementation was considering 3 consecutive phi bins for top and bottom SP search, but with wider phi bins, which would lead to more seeds. It should be studied though if this increase is worth the corresponding CPU increase.

**Comment by robertlangenberg** [comment]
Hi, I gave a response on a different ticket, to make it very short: (Nearly) the old behavior is achieved by setting
numPhiNeighbors=0 for the Grid and numPhiNeighbors=1 for the BinFinders. The name of the Grid configuration parameter is probably going to be changed in a future Acts release. 

https://github.com/acts-project/acts/pull/1167#issuecomment-1046799086

Please let us know if this fixes the problem and if yes close the github issue

**Comment by osbornjd** [comment]
Hi all, thanks for all the discussion! I think I learned quite a bit and in any case understand better the role of these parameter values. I believe Robert also correctly pointed out here:

> The name of the Grid configuration parameter is probably going to be changed in a future Acts release.

that part of my confusion was understanding the relationship between these two variables. I had assumed that there was an expectation that they be the same since they were named the same.

In any case I think the discussion cleared my own confusion and hopefully was valuable to you all as well, so we can close the issue.
