### ISSUE TITLE
Add examples CI jobs

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#155]
Add CI jobs that run a typical simulation and reconstruction chain using the examples

* [ ] Generate signal sample
* [ ] Add different pileup conditions
* [ ] Fatras simulation with the generic detector
* [ ] Fatras simulation with the ODD detector
* [ ] Run geometric hit digitization
* [ ] Run Gaussian smearing-based digitization
* [ ] Track fitting using truth tracks
* [ ] Track finding
* [ ] Vertexing using truth
* [ ] Vertexing using truth-fitted tracks
* [ ] Vertexing using reconstructed tracks
* [ ] Reintroduce the multi-threaded reproducibility tests #157

**Comment by paulgessinger** [comment]
New Feature and Infrastructure are mutually exclusive.

**Comment by paulgessinger** [comment]
Also we need to be careful how often to run these, if they take a non negligible amount of time.

**Comment by HadrienG2** [comment]
The number of simulated/reconstructed events should be a suitable tuning parameter to control how long the examples run. It's better to simulate few events in CI than to never run the code in CI at all.

Also, given how long the build itself takes, I would say that we have quite a margin of time we can spend on running examples before that activity becomes a non-negligible fraction of CI time...

Finally, note that this could be an occasion to bring back multi-threaded reproducibility tests.

**Comment by msmk0** [comment]
> Finally, note that this could be an occasion to bring back multi-threaded reproducibility tests.

@HadrienG2 Could you open an issue and link it from this one (as one additional point)

**Comment by HadrienG2** [comment]
I opened an issue (see link above), but I do not have permission to add it as a bullet point in the list above.

**Comment by msmk0** [comment]
Thanks, I added it to the list.

**Comment by HadrienG2** [comment]
It just occurred to me that someone interested in this issue might find the ["running examples" part of my acts docker image's auto-test routine](https://github.com/HadrienG2/spack-based-docker/blob/494c0907c033ccbe6fa81cda43d3558b186e65c0/acts/Dockerfile#L66) useful as a starting point.

**Comment by HadrienG2** [comment]
I'm looking into this at the moment.

**Comment by HadrienG2** [comment]
I have this on my medium-term TODO list.

**Comment by HadrienG2** [comment]
#706 is a significant step towards this.

**Comment by HadrienG2** [comment]
Since acts v6, we also have ActsExampleDigitizationGeneric to take care of here.

**Comment by HadrienG2** [comment]
By the way, for anyone interested in helping out (myself, I would tend to put priority on #157 since this is a part that only I can take care of)...

The CI routine for running examples is located in https://github.com/acts-project/acts/blob/master/CI/run_examples.sh . You can see that bash functions and variables are used to reduce redundancy when running multiple similar examples, please follow this discipline if possible, so that the script stays rather readable and when something needs to be changed it usually only needs changes in a single place. Also, please read the script's comments regarding our examples that support many different geometry configuration.

There is a list of TODOs at the bottom of the script that provides a relatively complete list of all examples that are not yet covered by CI. Relatively, because this list was written at the time where the script was added, and new examples have been added since.

For an example to run in CI, you must provide CLI flags of a configuration of a certain example that is known to work. For a couple of examples, such a configuration is described in https://acts.readthedocs.io/en/latest/howto/howto.html , but for others, either you know it already or you must figure it out through trial and error...

**Comment by HadrienG2** [comment]
I don't manage to move forward on this, so let's unassign myself.
