### ISSUE TITLE
Navigator: Resolving surfaces/layers/boundaries with bending tracks

### ISSUE THREAD

**Issue by benjaminhuth** [acts-project/acts#1596]
**Problem:**
I recently had a problem with the navigation, when experimented with a toy detector with alot of surfaces. 

The problem was that resolving layers/surfaces/boundaries is done via straight line intersection. With a large geometry and/or very bending tracks this can become a problem (see e.g. the following sketch for my case with the forward-backward pass of a fitter)

![image_2022_10_12T14_14_14_337Z](https://user-images.githubusercontent.com/37871400/195554689-31b5fcc3-1cba-404d-b9b9-2ff214583f74.png)

Now it turned out that this is also a problem e.g., in LDMX (@pbutti) with low momentum particles in a box volume, where sometimes boundaries are missed due to this issue.

**Solution**:
Since this is a problem also occuring in client code, I think that we shouldn't wait for the layerless geometry with that.

There are some possible solutions:
* Make the resolution stragegy configureable with the options `straight line` and `full`, which simply resolves all surfaces/layers/boundaries. We must check, if there could occur problems with the sorting of these surfaces by distance to the position.
* I think helix-extrapolation or something like that for the resolution would over-engineer the problem, but is also an option

@paulgessinger @asalzburger what do you think?

**Comment by paulgessinger** [comment]
First of all sorry to @pbutti for not realizing this was the same issue!

I think the pragmatic solution before the updated layer-less navigation is to add the full mode, off by default.

**Comment by benjaminhuth** [comment]
And we should add a Unit-Test that checks this, to make sure this is cached if the navigation code changes.

**Comment by benjaminhuth** [comment]
I could investigate this after the GSF thing, that has priority for me now

**Comment by pbutti** [comment]
Hi @benjaminhuth any progress on this? 
An intermediate proposal could be to add the possibility freely configure the envelopes of the layers.
I've made a commit https://github.com/acts-project/acts/compare/main...pbutti:acts:feat-TelescopeNavigationLayers
where I've set this up. This would be only used by the CuboidVolumeBuilder (good enough for simple detectors). I'm attaching 2 screenshots: the first shows the hit correctly associated to the sensitive surfaces, in the second, tagged "Before the fix", shows the missing hit. 
The missing hit is due to the linear extrapolation between navigation layers as discussed above.
I don't know if this issue is still present in v21, but while waiting for a better solution I can envision 2 possibilities:
- Enlarge the size of navigation layers (this commit)
- Put navigation layers closer to each other (not proposed)

Notice that this problem is not present in cylindrical geometries because they have 2pi coverage. 

What do you think
@paulgessinger @asalzburger 

![Screen Shot 2022-12-15 at 12 29 59 PM](https://user-images.githubusercontent.com/25535240/207848366-0de8c3ea-9ab1-4ddc-81eb-dd716e3db4b3.png)
![Screen Shot 2022-12-15 at 12 30 42 PM](https://user-images.githubusercontent.com/25535240/207848512-462905aa-7b11-410b-8996-c95b9aa4440e.png)
