### ISSUE TITLE
LCG compatibility

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#2054]
Our LCG compatibility doesn't look all that great right now.
We currently fail all of our clang builds with [compiler crashes](https://gitlab.cern.ch/acts/ci-bridge/-/jobs/29044714) and gcc12 seems to [throw some diagnostic](https://gitlab.cern.ch/acts/ci-bridge/-/jobs/29044722) against memory issues on some boost code that we use:

| LCG ver. | CentOS 7                                                  | CentOS 8 | ALMA9                   |
| -------- | --------------------------------------------------------- | -------- | ----------------------- |
| 101      | ✅ gcc10 <br/> ✅ gcc11 <br/> 🔴 clang12                  | ✅ gcc11 |                         | 
| 102b     | 🔴 gcc8 <br/> ✅ gcc11 <br/> 🔴 clang12                   | ✅ gcc11 | ✅ gcc11                |
| 103      | ✅ gcc11 <br/> 🔴 gcc12 <br/> 🔴 clang12 <br/> 🔴 clang15 |          | ✅ gcc11 <br/> 🔴 gcc12 |

**Comment by doloresgarcia** [comment]
Hi Paul, 
I seem to be having problems with 101, gcc11, CentOs 7 as well. This happens when I build the repository using the set up command:
`source CI/setup_cvmfs_lcg.sh`
and
`cmake -B build -S . -DACTS_BUILD_EXAMPLES=ON -DACTS_BUILD_EXAMPLES_PYTHON_BINDINGS=ON -DACTS_BUILD_ODD=ON -DACTS_BUILD_EXAMPLES_DD4HEP=ON`
I get the following error:
`CMake Error at CMakeLists.txt:289 (find_package):
  Could not find a configuration file for package "DD4hep" that is compatible
  with requested version "1.21".
  The following configuration files were considered but not accepted:
    /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/cmake/DD4hepConfig.cmake, version: 1.18`

**Comment by paulgessinger** [comment]
Hey @doloresgarcia.
The problem you observe specifically is that the DD4hep version in LCG 101 is unfortunately not high enough for recent versions of ACTS, we do indeed need DD4hep 1.21 and up.

Is it possible for you to switch to LCG 103, which I believe has a higher DD4hep version?

**Comment by doloresgarcia** [comment]
Thank you @paulgessinger, that solves the issue!

**Comment by paulgessinger** [comment]
Still on the list

**Comment by owtscharenko** [comment]
setting up on lxplus with `source CI/setup_cvmfs_lcg.sh` I get the same error regarding DD4hep. Is it possible to change the setup script in order to get the most recent LCG release with a higher DD4hep version?

**Comment by AJPfleger** [comment]
We dropped support for the mentioned versions with https://github.com/acts-project/acts/pull/3227
