### ISSUE TITLE
Proposal: MultiWire SurfaceCandidateUpdator

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#2063]
Based on some fantastic work from @dimitra97 - I suggest the following implementation of a first multi-wire layer

![Screenshot 2023-04-26 at 13 09 57](https://user-images.githubusercontent.com/26623879/234558213-afa5fabe-d20c-436f-818f-c56ea4c51533.png)

```c++
template <typename IndexedSurfacesGridType>
class MultiWireLayer : public INavigationDelegate {

  std::vector<std::shared_ptr<Surface>> m_gridSurfaces = {};
  IndexedSurfacesGridType m_indexedSurfaces;

};
```

Where, when entering a chamber and we call the navigation delegate, it does first:

```c++
std::vector<SurfaceIntersection> sIntersections;
sIntersections.reserve(m_gridSurfaces.size());
std::for_each(m_gridSurfaces.begin(), m_gridSurfaces.end(), [&] (const auto&s){... do intersection });
```

And then we use the intersection with the grid surfaces to provide the straws, when filling the grid, we can expand the surfaces into the neighbour bins so we have an artificial path through the multi chamber.

Does this make sense?

@noemina @andiwand

**Comment by dimitra97** [comment]
Hello,
Just an update about the grid before we move to the implementation of the navigation.
I created the two grids for the two multi layers, which are independent grids. I got the proto surfaces, the pGrid and the indices from the conversion, and as I understand this is all I need in order to get the registered surfaces.

So for example, I picked a random bin (e.g bin number 5) and what I get is the following:
`
- bin : [4, 4]
index = 111

`
and then I draw the surface that has that index (you can see it at the picture below, it is the pink colored surface). At the moment for a given bin, I get one index and one surface. I didn't do any expansion yet. 

![Screenshot from 2023-04-27 21-12-01](https://user-images.githubusercontent.com/63058524/234954870-73d5f2bb-93d4-470f-a42f-cabddcc1bfdb.png)

**Comment by asalzburger** [comment]
Impressive work, @dimitra97.

If one does e.g. track following, we have some dedicated direction through the chamber, so somehow we need to teach your navigation delegate to walk through the grid layers.

**Comment by dimitra97** [comment]
Hello,
here is an update of what happens when I add the bin expansion {1,1} for the 2d grid. So when I get a bin and the registered surfaces :
e.g 

` bin : [4, 4]
index = 74
index = 75
index = 76
index = 110
index = 111
index = 112
`

I also attach a screenshot
![Screenshot from 2023-05-02 19-42-01](https://user-images.githubusercontent.com/63058524/235730546-fc7c2316-0c1f-4953-8b60-f7dd11051a73.png)
Let me know if you think this is convenient for the navigation through the grid and for the test of the surfaces for intersection, so I guess I can proceed with the implementation of the navigation after that?
@noemina @asalzburger

**Comment by noemina** [comment]
@dimitra97, it looks very good to me! Yes, I guess you can start with implementing the navigation delegate. Further optimisation on the grid can be done afterwards.

**Comment by asalzburger** [comment]
This looks amazing, the bin expansion seems to work - what we need now is somehow to connect the bins, I made a bit of a sketch:

<img width="986" alt="Screenshot 2023-05-02 at 21 58 39" src="https://user-images.githubusercontent.com/26623879/235772678-a7bec244-505e-4677-ae1a-3d1d183a97df.png">

Imagine the black dotted line going through your chamber, what we'd like to get for a full navigation through is all the potential tubes that could be hit by it. I *think* we have to do this per multi-wire package.

**Comment by asalzburger** [comment]
From the the amount how far we look left-right per single grid layer can then be regulated by the bin expansion.

**Comment by asalzburger** [comment]
> Thank you both for the guidance. I only have a question: As I understand a possible implementation for the navigation can be by using the navigation state position and direction and I guess I can extrapolate to the vertical layers of the grid and pick the surfaces that are at the left/right side on each layer (regarding the bin expansion). Do you agree with that?
> 
> In that case, maybe we do not need the expansion along vertical axis? What do you think? Also, this should be done in a Surface Candidate updator, right?

I agree in omitting the vertical component.
As for the "propagation" - I think a full parameter propagation is too heavy and a simple bin-bin propagation could just do the trick as well.

If you arrive at your `MultiWireSurfaceCandidates` a simple `transform.inverse() * position` will put your position into the local frame where your wires are indexed, but also a `transform.inverse() * direction` will transfer your global direction into the local frame. (Reading this, we should actually store the transform already in the inverse version, because that's the way more frequent access pattern).

Now having your direction in the grid frame should give you `dx`, `dy` (we can ignore `dz`) and hence if you have the grid spacing `pX` and `pY`, you should be able with a simple function to calculate/predict:

-> position -> entry bin [ V, W ], the bin path through your multi wire chamber leading to a sequence

`[ V, W ], [ V + dV(dx,dy) , W + 1 ],   [ V + 2 * dV(dx,dy) , W + 2 ], ... [ V + N* dV(dx,dy) , W + N ]`

Where the progression on the y axis is always one layer to the next, and the local direction helps you to make the delta in X. This together with a bit of bin expansion should lead to all candidates at minimal computational cost.

**Comment by dimitra97** [comment]
Hello, and sorry for appearing after that long. I did some progress these weeks and implemented a surface candidates updator (will create a pr with that with a unittest) but before I could use some advice on the local transformation.
When I use the global position, but by forcing the navigation state to begin from the bottom of the grid along y axis I get the right results/surfaces.
However, when I try the local transformation I always get underflow bins (It probably considers it as global position)
I tried several options (using also the bin utility class). Here I show what I've tried and doesn't work. 

Without bin utility:
`
    auto minPos = grid.minPosition();

    Vector3 origin = Vector3(0, minPos[1],0);
    Translation3 trans(origin);
    Transform3 transform(trans);

//here I do the local position and direction transformation
    
    auto tposition = transform.inverse()*position;
    auto tdirection = transform.inverse()*direction;

    float dy = binWidth[1];
    auto phi = Acts::VectorHelpers::phi(tdirection);
    
      for(std::size_t i=0; i<nBins[1]; i++){
        std::cout<<"tposition="<<tposition.x()<<","<<tposition.y()<<","<<tposition.z()<<std::endl;

        auto lbin = grid.localBinsFromPosition(tposition);  
      
       auto extracted = extractor.extract(gctx, nState, grid.atLocalBins(lbin));

        Acts::Experimental::SurfacesFiller::fill(nState, extracted);

        tposition.x() = tposition.x()+dy/tan(phi);
        tposition.y() = tposition.y()+dy;
        


      }

`
and I also tried this style (because I saw that by giving a local position in the bin utility it can give you the bin):

```
Vector2 localposition = Vector2(tposition.x(),tposition.y());

   BinUtility binUtility2D(nBins[0],minPos[0],maxPos[0],open,binX);
    binUtility2D+=BinUtility(nBins[1],minPos[1], maxPos[1], open, binY);

//in the for loop
std::array<size_t,2> lbin = {binUtility2D.bin(localposition)+1,binUtility2D.bin(localposition,1)+1};
        auto extracted = extractor.extract(gctx, nState, grid.atLocalBins(lbin));     
```

I do not know if I am missing sth..but it is strange to me that the lbin value is always the same (an underflow bin) even if I move through the grid from a layer to the next (I checked that the t position is indeed changing). Any help/advice would be more than welcome!!
Thanks in advance!

**Comment by dimitra97** [comment]
Oh actually I made it work with the bin utility by only passing the transform in the constructor, so as I understand it does the transformation to the local frame internally and i don't do it in the code, only I create the origin of the grid frame. However, I don't know if this is the best solution (by using bin utility)

**Comment by AJPfleger** [comment]
Thanks for the great work. Should be finished with:
- https://github.com/acts-project/acts/pull/3041
