### ISSUE TITLE
SourceLink equality

### ISSUE THREAD

**Issue by andiwand** [acts-project/acts#2162]
While working on porting the Ambiguity Resolution to the Core I noticed that we do not have a mechanism to check two `SourceLink`s for equality.

I wonder if that is a design choice or if we would like to ask the user to provide such a functionality to us.

**Comment by tboldagh** [comment]
More than one needs to know about the equality and its pitfalls:
http://www.franktip.org/pubs/ecoop2007.pdf

**Comment by paulgessinger** [comment]
We had the minimal requirement for source link to have an associated geometry ID and nothing else. We didn't want to add a type erasure function call mechanism to keep it reasonably simple, that's why you have to downcast to do anything with it, really. 

It also encourages using explicit extension points like callbacks and delegate to inject experiment specific knowledge in well defined places. 

I'd be in favor of keeping this strategy.

**Comment by andiwand** [comment]
If we could have a similar mechanism for this like the type erasure in `Any` it would be good as we would not have a memory footprint in the `SourceLink` and the runtime overhead is similar to a function pointer.

But having an equality check within `Any` seems overkill and having a dedicated implementation for the `SourceLink` might be too much code duplication.

If we are fine by having delegates for handling this sort of things it is also good for me.

**Comment by paulgessinger** [comment]
Hm, I can't think of a way to implement that without a vtable lookup of some form, or implementing the delegate mechanism another time. 

We could theoretically attach a single delegate to a static variable in `SourceLink` but that's a bit of a singleton and I'm not sure that's a great idea either.

**Comment by andiwand** [comment]
Thanks for the discussion! I am good with the current solution. If we may end up pulling in such a mechanism in various different places we can re-open
