### ISSUE TITLE
bug: large errors in ODD track finding for theta = pi / 2

### ISSUE THREAD

**Issue by felix-russo** [acts-project/acts#2827]
Together with @andiwand, we noticed that the track finding/fitting in combination with the default seeding gives large errors for tracks that have `theta = pi / 2` when using the setup from our physics monitoring.

This can be nicely seen when plotting track errors against truth theta:
![image](https://github.com/acts-project/acts/assets/72298366/ff0ce3e7-9a8e-442a-82e9-38b918741080)

The tracks have no time measurements for theta approximately pi/2:
![image](https://github.com/acts-project/acts/assets/72298366/eb089e06-024a-4b4d-8694-e316be8d9e6b)

tagging @asalzburger @paulgessinger

**Comment by andiwand** [comment]
We digged a little bit more and it seems plausible that this is due to not having a correct initial time parameter from the seeding. The CKF will then reject measurements with time if they have a big residual which happens by chance. The result is tracks without any pixel measurements and poor IP resolution

**Comment by felix-russo** [comment]
Also tagging our seeding expert @LuisFelipeCoelho 😄

**Comment by andiwand** [comment]
I should also mention https://github.com/acts-project/acts/pull/2829 here. There I wire the measurement time through SP and seeds so this effect should go away

**Comment by AJPfleger** [comment]
dev-meeting: @andiwand: this is probably fixed. If time estimation was too stiff, we ould not find a track in the region.
