### ISSUE TITLE
DD4hep plugin and dd4hep surfaces/segmentations

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#363]
Hello,

Does ACTS dd4hep plugin use dd4hep-surfaces when converting the geometry?

Also, does the plugin use the dd4hep-segmentation geometry, for example, in constructing the pixel sizes?

Thanks

**Comment by paulgessinger** [comment]
@asalzburger did you see this?

**Comment by asalzburger** [comment]
Ah apologies, this slipped through my radar.

What we did for the FCC-hh is to translate the segmentation into Acts-Digitisation modules, which then are used for further segmentation handling.

Simply the geometry aspect does NOT use the segmentation, since we leave the actual readout segmentation to be a virtual construct (and model the sensor as a single surface).  I am actually re-writing the geometric digitisation (simplify it), and plan to attach the segmentation for pixel clustering and channel identification in an even easier way using the new flat GeometryID container introduced by @msmk0.

Then, eventually, one would have to translate the dd4hep::segmentation simply into a `Acts::BinUtility` description - I expect this to appear within the next 2 weeks as a PR.

**Comment by whit2333** [comment]
@asalzburger Thanks for update.

What about "dd4hep surfaces"? Conceptually, maybe these are more like "ACTS layers". They are easy to add in the dd4hep geometry constructor and seems like they could be directly translated into ACTS? 

Overall, I am hoping that dd4hep + ACTS will not require another geometry tool beyond dd4hep. Is it fair to say that, currently, the dd4hep conversion is minimal, and in the future, all tracking geometry could be converted from dd4hep (+ACTSExtension)?

Cheers

**Comment by whit2333** [comment]
See my comment [here](https://github.com/acts-project/acts/issues/372#issuecomment-675042296) about segmentations.
Essentially, the segmentation concept is not needed in Acts if dd4hep is being used. The sensor hit position and covariance are easily transferred with the dd4hep facilities.

**Comment by whit2333** [comment]
> Ah apologies, this slipped through my radar.
> 
> What we did for the FCC-hh is to translate the segmentation into Acts-Digitisation modules, which then are used for further segmentation handling.
> 
> Simply the geometry aspect does NOT use the segmentation, since we leave the actual readout segmentation to be a virtual construct (and model the sensor as a single surface). I am actually re-writing the geometric digitisation (simplify it), and plan to attach the segmentation for pixel clustering and channel identification in an even easier way using the new flat GeometryID container introduced by @msmk0.
> 
> Then, eventually, one would have to translate the dd4hep::segmentation simply into a `Acts::BinUtility` description - I expect this to appear within the next 2 weeks as a PR.

@asalzburger Did this ever get implemented?

**Comment by asalzburger** [comment]
The first part will be contained in #652, which will allow to use an arbitrary segmentation based on a `BinUtility` for planar surfaces. 

Also, we have discussed yesterday coincidently the format for the `json` file for loading different digitisation parameters for various detector regions, but this will only come in a follow-up PR.
