### ISSUE TITLE
Bug: MagField with 0 z-component causes vector::_M_default_append when Acts::SpacePointGridCreator::createGrid is called

### ISSUE THREAD

**Issue by CarloVarni** [acts-project/acts#764]
While studying the seeding algorithm in ActsExamples I entered a magnetic filed with 0 as z-component and this resulted in a `vector::_M_default_append` error message.

The error arises in Acts::SpacePointGridCreator::createGrid (see https://github.com/acts-project/acts/blob/master/Core/include/Acts/Seeding/SpacePointGrid.ipp#L15). In here there is no protection against such a case and several divisions by zero occurs, which result in phiBins being -2147483648 (in my case at least) and the error message when the SpacePointGrid object is created (i.e. https://github.com/acts-project/acts/blob/master/Core/include/Acts/Seeding/SpacePointGrid.ipp#L50).

**Comment by paulgessinger** [comment]
I **think** the seed finding implementation assumes a non-zero B field a long the z-axis, as it bases most of it's calculations on an assumed helix trajectory. If that is the case, I don't think we can do much better than checking for this and throwing a more informative error.

**Comment by robertlangenberg** [comment]
The seeding doesn't actually require a magnetic field, but since you specifically mention 0 field only along the z component: the seeding algorithm will NOT work with (significant) magnetic field along any other axis BUT the z axis, if you do have magnetic field along a different axis you will have to rotate the space. 

The SpacePointGridCreator is a helper not really related to the seeding algorithm itself, and it crashing with no magnetic field is indeed a bug.
