### ISSUE TITLE
cmake searches for boost in config mode

### ISSUE THREAD

**Issue by andriish** [acts-project/acts#886]
I have a properly installed boost-1.75 in Fedora35/rawhide, but cmake searches boost in CONFIG mode and cannot find it.

removal of 'CONFIG' fixes the issue.

Best regards,

Andrii

**Comment by paulgessinger** [comment]
I've looked into this a bit. It seems Fedora packages do not generally provide `XConfig.cmake` files. This means a ton of manual massaging to get cmake to find packages. I was unable to even build DD4hep without massive effort, configuration of it alongside ROOT and Geant4 turned out to be very complicated.

If there are no objections, I would tend to just not support Fedora, as we don't want to ship a bunch of `FindX.cmake` files, and my understanding that behavior is legacy anyway.

Thoughts?

**Comment by andriish** [comment]
Hi @paulgessinger ,

eh,  I'm confused. There is no need to provide anything. FindBoost is in cmake since a very long time
https://cmake.org/cmake/help/latest/module/FindBoost.html
Neither Fedora nor other distributions with *modern* cmake should use config mode.
Things work fine w/o the CONFIG keyword, which does not appear anywhere in the cmake documentation for FindBoost.

DD4hep, Geant4 and root are not related, but:

> DD4hep 

It has issues with installation paths, but otherwise it is fine. At least with newest cmake
https://github.com/andriish/HEPrpms/blob/master/DD4hep/01.17.00/DD4hep.spec

> Geant4 

Is fine as is modulo small issue with python.

> root

Is present in the repositories.



Best regards,

Andrii

**Comment by paulgessinger** [comment]
I tried Geant4 and ROOT from RPMSphere, both of which appear broken. DD4hep needs G4 and ROOT, that's where I have trouble. I don't have experience with Fedora, and don't have time right now to build both from source.

Cmake CONFIG mode supersedes MODULE mode, so modern packages should migrate towards shipping with `XConfig.cmake`, so that downstream projects don't need to ship with a `FindX.cmake`.

**Comment by paulgessinger** [comment]
Anyway, I can merge a fix for Boost, but it seems like a Fedora build without dependencies built from source won't work anyway, so I'm not sure it's worth it.

**Comment by paulgessinger** [comment]
Ah, btw, looking at the CMake documentation you linked, it says all the way below that newer versions of Boost do ship with `BoostConfig.cmake`, and `FindBoost.cmake` will actually first look for the config file.

**Comment by andriish** [comment]
Hi @paulgessinger ,

> this is actively stripped from Fedora packages.

That might be the case. My understanding is that  CONFIG should not be used in any case as you've correctly mentioned
 
> FindBoost.cmake will actually first look for the config file.

w/o any keywords. But w/o any keywords the FindBoost will work also if `BoostConfig.cmake` is not found.

**Comment by andriish** [comment]
Hi @paulgessinger ,

> I can merge a fix for Boost

would you merge #909 ? This would reduce the build script @ Fedora by 1 line....

Andrii

**Comment by gagnonlg** [comment]
@andriish I will have a look at #909 later today

**Comment by gagnonlg** [comment]
@andriish @paulgessinger I just looked into this a bit. There is this variable: https://cmake.org/cmake/help/v3.15/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html

Presumably setting it to TRUE causes find_package to use CONFIG mode even when not specified, but falls back to the find* behavior if that does not work. Naively this seems to be exactly what we need.

@andriish can you try setting this variable?
@paulgessinger This would bump our minimal cmake version to 3.15 (unless we add a conditional block for the version). Thoughts?

**Comment by andriish** [comment]
No special variableas or version bumps  are needed. The stock FindBoost has desired behaviour, see cmake docs. Just merge #909.

**Comment by paulgessinger** [comment]
@gagnonlg I think `CMAKE_FIND_PACKAGE_PREFER_CONFIG` is actually what we want, yeah. The only potential problem with CMake 3.15 is that our currently lowest "supported" LCG version is 97apython3, which ships with CMake 3.14.3. 

I guess we could think about dropping LCG97apython3 though, and then we're free to bump and do this.

**Comment by andriish** [comment]
> ships with CMake 3.14.3

https://cmake.org/cmake/help/v3.14/module/FindBoost.html

```
If Boost was built using the boost-cmake project it provides a package configuration file for use with find_package’s Config mode. This module looks for the package configuration file called BoostConfig.cmake or boost-config.cmake and stores the result in cache entry “Boost_DIR”. If found, the package configuration file is loaded and this module returns with no further action. See documentation of the Boost CMake package configuration for details on what it provides.

Set Boost_NO_BOOST_CMAKE to ON to disable the search for boost-cmake.
```
So #909 has the desired behaviour for the supported versions and does the job.

Moreover, I don't even know (because there are no docs!) on the interaction between `CMAKE_FIND_PACKAGE_PREFER_CONFIG` and `Boost_NO_BOOST_CMAKE`.


Best regards,

Andrii

**Comment by andriish** [comment]
For FindBoost

" " means "search in CONFIG mode and then in MODULE"

 "CONFIG" means "search only in CONFIG mode"

For all supported versions.

Hopefully this is a good explantion.

Best regards,

Andrii

**Comment by robertlangenberg** [comment]
I agree CMAKE_FIND_PACKAGE_PREFER_CONFIG is the way to go. Before dropping LCG97apython3 we should at least discuss in the Tuesday meeting if someone thinks this should still be supported, and we should probably wait until @asalzburger is back.

@andriish @paulgessinger There seems to be some confusion, if CONFIG mode is the recommended way and FindX is deprecated, we should focus on supporting CONFIG mode. 

All in all, this doesn't seem particularly urgent given the simple workaround, so this if there are still Acts users who require LCG97apython3 we might have to postpone adding a fix.

**Comment by andriish** [comment]
> if CONFIG mode is the recommended way

Where exactly?  What do you mean exactly?

> FindX is deprecated 

?

Now I'm really confused. Could you, please, give some reference to the documentation? Other wise your claims look completely unsupported.


Best regards,

Andrii

**Comment by gagnonlg** [comment]
@andriish as far as I can tell the Boost_NO_BOOST_CMAKE option is not a cmake env var that can be set with -D and we don't use it in our configuration so the point is moot. The CMAKE_FIND_PACKAGE_PREFER_CONFIG variable should do exactly what you want and future-proof our build configuration in the event that FindBoost.cmake is deprecated (I could not find any official word on this but discussion on the cmake forums, stackoverflow and elsewhere strongly hints towards that in the future since boost now supplies its own files to work with CONFIG mode since 1.70). So I don't really see what we're arguing about here.

@robertlangenberg If we want to keep supporting boost 3.14 we could set this variable conditional on the cmake version?

Cheers
L-G

**Comment by andriish** [comment]
Hi @gagnonlg ,

this issue is not a big deal at all and I'm not using acts at all and I don't like discussions for the sake of discussions, but
for me that is interesting that we have completely different understanding of  the same, very clear documentation of cmake. 

> Boost_NO_BOOST_CMAKE option is not a cmake env var that can be set with -D and we don't use it in our configuration so the point is moot. 

It is. The docs say exactly that. But if you don't trust the official docs, look how people use it https://www.google.com/search?q=DBoost_NO_BOOST_CMAKE

> CMAKE_FIND_PACKAGE_PREFER_CONFIG

Again,  FindBoost in all versions works as if this variable is set to TRUE. See  docs on FindBoost.  No need to set it explicitly. And well, that makes no sense for cmake 3.14.

> I could not find any official word on this
>but discussion on the cmake forums, stackoverflow and elsewhere

That is the point of the official docs -- one should follow them and not what strangers write on various internet sites.

Best regards,

Andrii

**Comment by gagnonlg** [comment]
Hi @andriish, thanks for the clarification. I probably misunderstood what Boost_NO_BOOST_CMAKE does, it does nothing in my installation and cmake points it out to me but I think that's because I use the boost-provided config, not findboost. 

The main advantage I see of doing CMAKE_FIND_PACKAGE_PREFER_CONFIG is that in the event that one has a boost installation that supplies a cmake configuration it will use that instead; if the boost developers feel that it's necessary for them to supply their configuration I think it makes sense for us to use it, and fall back to the findboost stuff if needed. I think it's a reasonable middle ground, don't you think?

Best,
L-G

**Comment by andriish** [comment]
> I think it's a reasonable middle ground, don't you think?

I do!  And that is the default behaviour if the 'CONFIG' keyword is NOT present in the call.

My understanding is that 

#909  will work as follows:
   cmake <3.14
    - FindBoost.cmake is present and used
    - load boost-provided config if found, otherwise do the search in  boring way
   3.14<cmake<3.X
    - FindBoost.cmake is present and used
    - load boost-provided config if found, otherwise do the search in  boring way
   3.X<cmake, i.e. FindBoost from cmake is deprecated and removed, just as the rumors in the internet say
    -   FindBoost.cmake is NOT present
    -  find_package fails in 'MODULE' mode and falls back to 'CONFIG' mode. This can be skipped with `CMAKE_FIND_PACKAGE_PREFER_CONFIG`
    -  load boost-provided config if found, otherwise fail

vs. how it works in master 

   cmake <3.14
    - FindBoost.cmake is present but NOT used
    - load boost-provided config if found,  otherwise fail
   3.14<cmake<3.X
    - FindBoost.cmake is present but NOT used
    - load boost-provided config if found, otherwise fail
   3.X<cmake, i.e. FindBoost from cmake is deprecated and removed, just as the rumors in the internet say
    -  FindBoost.cmake is NOT present
    -  load boost-provided config if found,  otherwise fail

So #909 has a clear advantage for all existing cmake versions and behaves in the same way for 3.X<cmake.
 The thing is that as of *now*  X is not known and for sure X>22.

Best regards,

Andrii

**Comment by gagnonlg** [comment]
Hi @andriish , thanks for the write up. I'm not a cmake expert at all, and I actually thought that CONFIG and "Module" modes were mutually exclusive for find_package, but I've re-read the documentation and it seems like the option I'm proposing only switch the order of preference of the two. Seems to me like this is too small an improvement to justify dropping cmake <3.15, at least for the time being.

@paulgessinger @robertlangenberg I'd say we should just merge #909?

Cheers,
L-G

**Comment by paulgessinger** [comment]
Ok
